version: '3.8'

services:
  app:
    image: php:8.3-fpm
    container_name: php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - symfony

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony

  database:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - symfony

volumes:
  pgdata:

networks:
  symfony:
